#!/bin/bash

# user-defined variables
orig_English="orig_English.txt"
orig_Russian="orig_Russian.txt"

# internal script variables
temp_FileNotFound=0

for temp_var in $orig_English $orig_Russian
    do
        if [ -f $temp_var ]
            then
                echo "FOUND:     " $temp_var
            else
                temp_FileNotFound=1
                echo "NOT FOUND: " $temp_var
        fi
    done

if [ $temp_FileNotFound -eq 1 ]
    then
        echo "-----------"
        echo "Exit code: file(s) not found"
        exit 0
fi
