#!/bin/bash

function exit_with_error {
    local local_errorcode
    local_errorcode=("$@")
    echo "------------------------------"
    echo ${local_errorcode[*]}
    echo "Exit..."
    exit 0
}

function find_string_in_string {                # 1) substring 2) string
    if grep -q $1 <<< $2
    then
        echo 1
    else
        echo 0
    fi
}

function cut_kavichki {                         # 1) string to cut
    echo $1 | cut -d'"' -f2
}

if ! [ -n "$1" ]
then
    error_code="Please add a filename"
    exit_with_error ${error_code[*]}
fi

if ! [ -f $1 ]
then
    error_code="NOT FOUND: $1"
    exit_with_error ${error_code[*]}
fi

IFS=$'\n'
for string in $(cat $1)
    do
        result=$(find_string_in_string "string m_Name" $string)

        if [ $result == 1 ]
        then
            afterCUT=$(cut_kavichki $string)
            filename="orig_$afterCUT formatted.csv"
            echo 'Key,'$afterCUT',NOTES,'$filename',
,,,,,,,,,,,,,,,,,,,
UseCyrillicFont,No,"Пометка для переводчиков: поставьте на позиции (между разделителями) вашего языка ""Yes"", если используете кириллицу",Yes,
,,,,,,,,,,,,,,,,,,,' > $(echo $filename)
            break
        fi

    done
