#!/bin/bash

function exit_with_error {
    local local_errorcode
    local_errorcode=("$@")
    echo "------------------------------"
    echo ${local_errorcode[*]}
    echo "Exit..."
    exit 0
}

function find_string_in_string {                # 1) substring 2) string
    if grep -q $1 <<< $2; then
        echo 1
    else
        echo 0
    fi
}

function cut_kavichki {                         # 1) string to cut
    echo $1 | cut -d'"' -f2
}

echo "------------------------------"
echo "Prepare..."
if ! [ -n "$1" ]; then
    error_code="Please add a filename"
    exit_with_error ${error_code[*]}
fi

if ! [ -f $1 ]; then
    error_code="NOT FOUND: $1"
    exit_with_error ${error_code[*]}
fi

IFS=$'\n'

# making the first few mandatory lines
echo "Making the first few mandatory lines..."
for string in $(cat $1); do
    result=$(find_string_in_string "string m_Name" $string)

    if [ $result == 1 ]; then
        afterCUT=$(cut_kavichki $string)
        filename="orig_$afterCUT formatted.csv"
        echo 'Key,'$afterCUT',NOTES,'$filename',
,,,,,,,,,,,,,,,,,,,
UseCyrillicFont,No,"Пометка для переводчиков: поставьте на позиции (между разделителями) вашего языка ""Yes"", если используете кириллицу",Yes,
,,,,,,,,,,,,,,,,,,,' > $(echo $filename)
        break
    fi
done

# check total amount of KEYS
string_counter=0

for string in $(cat $1); do
    result=$(find_string_in_string "int size" $string)

    if [ $result == 1 ]; then
        if [ $string_counter == 0 ]; then
            let string_counter++
        else
            string_counter=$(echo $string | sed s/[^0-9]//g)
            echo "KEYS total....................."$string_counter
            break
        fi
    fi
done

# making KEYS + ingame strings
echo -ne "Making KEYS + ingame strings...\r"
string_counter=0

for string in $(cat $1); do
    if [ $(find_string_in_string "string m_Key" $string) == 1 ]; then
        afterCUT=$(cut_kavichki $string)
        echo -n $afterCUT',' >> $(echo $filename)
    elif [ $(find_string_in_string "string data" $string) == 1 ]; then
        if [ $string_counter != 0 ]; then
            echo -ne "Making KEYS + ingame strings..."$string_counter"\r"
            afterCUT=$(cut_kavichki $string)
            echo '"'$afterCUT'",,,' >> $(echo $filename)
        fi
        let string_counter++
    fi
done

echo -e "\n------------------------------"
echo "DONE!"
echo "------------------------------"
